#!/bin/bash

#SBATCH --job-name=annotate-propaganda    # Job name
#SBATCH --output=propaganda_detect.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --gres=gpu               # Schedule a GPU, or more with gpu:2 etc
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown    # Run on either the Red or Brown queue

python propaganda_detection.py